"""Command-line interface: ``python -m synaptic <command>``.

Subcommands
    status                              health + recorded-keyspace counts
    ingest   HINTS                      write a hint set into the graph
    generate HINTS [--out FILE]         emit a btcrecover tokenlist
    recover  HINTS --wallet KEY [...]   run one recovery step
    runs     [--wallet-label L]         list recent runs

Connection comes from the environment (see :mod:`synaptic.config`). The recovered
password is never printed - on success the checker's restricted
``RECOVERED_PASSWORD.txt`` is written and its path is reported.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import tempfile

from . import coverage, schema
from .client import SynapCoresClient, SynapCoresError
from .config import Settings
from .generate import write_tokenlist
from .hints import build_graph, load_hints, read_hints_from_graph
from .recover import recent_runs, recover, wallet_id_by_label


def _client() -> SynapCoresClient:
    settings = Settings.from_env()
    if not settings.has_credentials():
        sys.exit(
            "No credentials: set SYNAPCORES_TOKEN or SYNAPCORES_PASSWORD (see synaptic/README.md)."
        )
    return SynapCoresClient(settings)


def cmd_status(args: argparse.Namespace) -> int:
    client = _client()
    health = client.health()
    print(f"SynapCores at {client.settings.url}: {health.get('status')}")
    schema.bootstrap(client)
    if args.wallet_label:
        wid = wallet_id_by_label(client, args.wallet_label)
        if wid:
            print(f"wallet '{args.wallet_label}' ({wid}):", coverage.coverage_report(client, wid))
        else:
            print(f"no wallet registered with label '{args.wallet_label}'")
    else:
        total = client.sql_scalar("SELECT COUNT(*) FROM sc_wallets") or 0
        runs = client.sql_scalar("SELECT COUNT(*) FROM sc_runs") or 0
        print(f"wallets registered: {total} | runs recorded: {runs}")
    return 0


def cmd_ingest(args: argparse.Namespace) -> int:
    client = _client()
    schema.bootstrap(client)
    hint_set = load_hints(args.hints)
    build_graph(client, hint_set)
    hints = read_hints_from_graph(client, hint_set.wallet_label)
    print(
        f"ingested {len(hints)} hints for '{hint_set.wallet_label}' "
        f"(delimiters={hint_set.delimiters!r}):"
    )
    for hint in hints:
        flag = "required" if hint.required else "optional"
        print(f"  [{flag:8}] w={hint.weight} {hint.kind:8} {hint.text!r}")
    return 0


def cmd_generate(args: argparse.Namespace) -> int:
    hint_set = load_hints(args.hints)
    out = args.out or f"synaptic_tokens_{hint_set.wallet_label}.txt"
    text = write_tokenlist(
        out,
        hint_set.hints,
        hint_set.delimiters,
        header=f"generated by synaptic for {hint_set.wallet_label}",
    )
    print(f"wrote tokenlist -> {out}\n")
    print(text, end="")
    return 0


def cmd_recover(args: argparse.Namespace) -> int:
    client = _client()
    hint_set = load_hints(args.hints)
    workdir = args.workdir or tempfile.mkdtemp(prefix="synaptic_")
    report = recover(
        client,
        hint_set,
        args.wallet,
        workdir=workdir,
        ranker=args.ranker,
        skip_covered=not args.no_skip_covered,
        max_checks=args.max_checks,
    )
    _print_report(report)
    return 0 if report.found else 2


def _print_report(report) -> None:
    print("\n== synaptic recovery report ==")
    print(f"  wallet         : {report.wallet_label} ({report.wallet_id})")
    print(
        f"  ranker         : {report.ranker}"
        + (f" (model accuracy {report.accuracy})" if report.accuracy else "")
    )
    print(f"  candidates     : {report.num_candidates}")
    print(f"  new (unseen)   : {report.num_new}")
    print(f"  skipped covered: {report.num_skipped}")
    print(f"  checked        : {report.checked}  in {report.elapsed_seconds}s")
    print(f"  tokenlist      : {report.tokenlist_path}")
    if report.found:
        print(f"  RESULT         : FOUND at ranked position {report.found_position}")
        print(
            "                   password written to RECOVERED_PASSWORD.txt (not shown, not stored)"
        )
    else:
        print("  RESULT         : not found in this candidate set")


def cmd_forget(args: argparse.Namespace) -> int:
    client = _client()
    schema.bootstrap(client)
    wid = wallet_id_by_label(client, args.wallet_label)
    if not wid:
        print(f"no wallet registered with label '{args.wallet_label}'")
        return 1
    before = coverage.forget(client, wid)
    print(f"forgot coverage for '{args.wallet_label}' ({wid}): {before}")
    return 0


def cmd_runs(args: argparse.Namespace) -> int:
    client = _client()
    schema.bootstrap(client)
    rows = recent_runs(client, args.wallet_label, limit=args.limit)
    if not rows:
        print("no runs recorded yet")
        return 0
    print(json.dumps(rows, indent=2, default=str))
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m synaptic",
        description="SynapCores-backed intelligence layer for BitCracker V2.",
    )
    p.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help="-v for info, -vv for debug diagnostics (to stderr)",
    )
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("status", help="show health and recorded-keyspace counts")
    s.add_argument("--wallet-label")
    s.set_defaults(func=cmd_status)

    s = sub.add_parser("ingest", help="write a hint set into the graph")
    s.add_argument("hints")
    s.set_defaults(func=cmd_ingest)

    s = sub.add_parser("generate", help="emit a btcrecover tokenlist from hints")
    s.add_argument("hints")
    s.add_argument("--out")
    s.set_defaults(func=cmd_generate)

    s = sub.add_parser("recover", help="run one recovery step")
    s.add_argument("hints")
    s.add_argument("--wallet", required=True, help="MultiBit Classic .key file")
    s.add_argument("--ranker", choices=["heuristic", "automl", "auto"], default="heuristic")
    s.add_argument(
        "--no-skip-covered",
        action="store_true",
        help="re-check candidates already tried for this wallet",
    )
    s.add_argument("--max-checks", type=int, help="stop after N candidates")
    s.add_argument("--workdir")
    s.set_defaults(func=cmd_recover)

    s = sub.add_parser("runs", help="list recent runs")
    s.add_argument("--wallet-label")
    s.add_argument("--limit", type=int, default=10)
    s.set_defaults(func=cmd_runs)

    s = sub.add_parser("forget", help="delete stored coverage + runs for a wallet")
    s.add_argument("--wallet-label", required=True)
    s.set_defaults(func=cmd_forget)
    return p


def _configure_logging(verbosity: int) -> None:
    level = {0: logging.WARNING, 1: logging.INFO}.get(verbosity, logging.DEBUG)
    logging.basicConfig(level=level, format="%(levelname)s %(name)s: %(message)s")
    # Set the package logger level explicitly so verbosity applies even when the
    # root logger was already configured (e.g. under a test runner).
    logging.getLogger("synaptic").setLevel(level)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    _configure_logging(getattr(args, "verbose", 0))
    try:
        return args.func(args)
    except SynapCoresError as exc:
        sys.exit(f"SynapCores error: {exc}")
    except FileNotFoundError as exc:
        sys.exit(f"file not found: {exc}")


if __name__ == "__main__":
    raise SystemExit(main())
