"""The recovery orchestrator. recover() runs one full campaign step:

1. bootstrap the schema and register the wallet (its salt doubles as the id).
2. write the hints into the property graph, then read them back (GraphRAG).
3. generate a tokenlist and enumerate its candidates with the checker's parser.
4. drop candidates already tried for this wallet.
5. rank the rest (heuristic or in-database AutoML).
6. check them in ranked order, in-process, stopping at the first hit.
7. record the run and the tried candidates (never the password) in SQL.

It returns a small report: how many candidates were skipped as already-covered,
which ranker ran, and where the password sat in the ranking if found.
"""

from __future__ import annotations

import hashlib
import logging
import os
import time
import uuid
from dataclasses import asdict, dataclass
from datetime import datetime, timezone

from . import bitcracker, coverage, schema
from .client import SynapCoresClient, sql_literal
from .generate import write_tokenlist
from .hints import HintSet, build_graph, read_hints_from_graph
from .rank import AutoMLRanker, HeuristicRanker

_log = logging.getLogger("synaptic.recover")


@dataclass
class RunReport:
    run_id: str
    wallet_id: str
    wallet_label: str
    num_candidates: int
    num_new: int
    num_skipped: int
    checked: int
    found: bool
    found_position: int | None
    ranker: str
    accuracy: float | None
    elapsed_seconds: float
    tokenlist_path: str

    def as_dict(self) -> dict:
        return asdict(self)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def wallet_id_by_label(client: SynapCoresClient, label: str) -> str | None:
    """Resolve a wallet label to its id, quoting the label via sql_literal.

    Centralized so every label lookup uses the same safe quoting instead of ad
    hoc f-string interpolation.
    """
    return client.sql_scalar(f"SELECT id FROM sc_wallets WHERE label = {sql_literal(label)}")


def _register_wallet(
    client: SynapCoresClient, wallet_id: str, label: str, wallet_type: str, salt_hex: str
) -> None:
    exists = client.sql_scalar(
        f"SELECT COUNT(*) FROM sc_wallets WHERE id = {sql_literal(wallet_id)}"
    )
    if exists:
        client.sql(
            f"UPDATE sc_wallets SET label = {sql_literal(label)} "
            f"WHERE id = {sql_literal(wallet_id)}"
        )
    else:
        client.sql(
            "INSERT INTO sc_wallets (id, label, wallet_type, salt_hex, created_at) "
            f"VALUES ({sql_literal(wallet_id)}, {sql_literal(label)}, "
            f"{sql_literal(wallet_type)}, {sql_literal(salt_hex)}, {sql_literal(_now())})"
        )


def _make_ranker(name: str, client: SynapCoresClient, hint_set: HintSet):
    if name == "auto":
        return AutoMLRanker(client, delimiters=hint_set.delimiters)
    if name == "automl":
        return AutoMLRanker(client, delimiters=hint_set.delimiters)
    return HeuristicRanker(client, delimiters=hint_set.delimiters)


def recover(
    client: SynapCoresClient,
    hint_set: HintSet,
    wallet_path: str,
    workdir: str,
    ranker: str = "heuristic",
    skip_covered: bool = True,
    max_checks: int | None = None,
) -> RunReport:
    """Run one recovery step and return a RunReport."""
    started = time.monotonic()
    run_id = uuid.uuid4().hex
    schema.bootstrap(client)

    wallet = bitcracker.load_wallet(wallet_path)
    salt_hex = wallet.salt.hex()
    wallet_id = salt_hex  # stable per-wallet id; not a secret
    _register_wallet(client, wallet_id, hint_set.wallet_label, hint_set.wallet_type, salt_hex)

    tokenlist_path = os.path.join(workdir, f"synaptic_tokens_{wallet_id}.txt")
    tl_hash = hashlib.sha256(tokenlist_path.encode()).hexdigest()[:16]
    # Record the run up front so a failure mid-step still leaves an auditable row.
    _start_run(client, run_id, wallet_id, tl_hash)

    num_candidates = num_new = num_skipped = checked = 0
    found = False
    found_position: int | None = None
    accuracy: float | None = None
    notes = "ok"
    try:
        # Graph is the source of truth: write hints, then read them back.
        build_graph(client, hint_set)
        hints = read_hints_from_graph(client, hint_set.wallet_label) or hint_set.hints
        write_tokenlist(
            tokenlist_path,
            hints,
            hint_set.delimiters,
            header=f"generated by synaptic for {hint_set.wallet_label}",
        )
        candidates = bitcracker.enumerate_candidates(tokenlist_path)
        num_candidates = len(candidates)

        if skip_covered:
            new_candidates, already = coverage.partition(client, wallet_id, candidates)
        else:
            new_candidates, already = list(candidates), []
        num_new, num_skipped = len(new_candidates), len(already)
        _log.info(
            "wallet %s: %d candidates, %d new, %d already covered",
            wallet_id,
            num_candidates,
            num_new,
            num_skipped,
        )

        ranker_impl = _make_ranker(ranker, client, hint_set)
        scored = ranker_impl.rank(new_candidates)
        accuracy = getattr(ranker_impl, "accuracy", None)

        limit = max_checks if max_checks is not None else len(scored)
        for idx, (candidate, _score) in enumerate(scored):
            if checked >= limit:
                break
            checked += 1
            if wallet.check(candidate):
                found = True
                found_position = idx + 1
                bitcracker.write_found_password(candidate, cwd=workdir)
                break

        coverage.record(
            client, wallet_id, run_id, scored[:checked], delimiters=hint_set.delimiters, tried=True
        )
    except Exception as exc:  # noqa: BLE001 - finalize the run row, then re-raise
        notes = f"error: {type(exc).__name__}: {exc}"[:300]
        raise
    finally:
        elapsed = time.monotonic() - started
        rate = checked / elapsed if elapsed > 0 else 0.0
        _finish_run(client, run_id, num_candidates, num_new, checked, found, rate, notes)

    return RunReport(
        run_id=run_id,
        wallet_id=wallet_id,
        wallet_label=hint_set.wallet_label,
        num_candidates=num_candidates,
        num_new=num_new,
        num_skipped=num_skipped,
        checked=checked,
        found=found,
        found_position=found_position,
        ranker=ranker,
        accuracy=accuracy,
        elapsed_seconds=round(elapsed, 3),
        tokenlist_path=tokenlist_path,
    )


def _start_run(client: SynapCoresClient, run_id: str, wallet_id: str, tl_hash: str) -> None:
    client.sql(
        "INSERT INTO sc_runs (id, wallet_id, tokenlist_hash, num_candidates, "
        "num_new, checked, found, rate, engine, started_at, finished_at, notes) "
        f"VALUES ({sql_literal(run_id)}, {sql_literal(wallet_id)}, {sql_literal(tl_hash)}, "
        f"0, 0, 0, 0, 0.0, 'synaptic-inproc', {sql_literal(_now())}, NULL, 'in-progress')"
    )


def _finish_run(
    client: SynapCoresClient,
    run_id: str,
    num_candidates: int,
    num_new: int,
    checked: int,
    found: bool,
    rate: float,
    notes: str,
) -> None:
    client.sql(
        "UPDATE sc_runs SET "
        f"num_candidates = {num_candidates}, num_new = {num_new}, checked = {checked}, "
        f"found = {1 if found else 0}, rate = {rate!r}, "
        f"finished_at = {sql_literal(_now())}, notes = {sql_literal(notes)} "
        f"WHERE id = {sql_literal(run_id)}"
    )


def recent_runs(
    client: SynapCoresClient, wallet_label: str | None = None, limit: int = 10
) -> list[dict]:
    """Return recent runs (most recent first) as dicts, for recall/reporting."""
    where = ""
    if wallet_label:
        wid = wallet_id_by_label(client, wallet_label)
        if wid:
            where = f"WHERE wallet_id = {sql_literal(wid)}"
    rows = client.sql(
        "SELECT id, wallet_id, num_candidates, num_new, checked, found, "
        f"rate, started_at FROM sc_runs {where} ORDER BY started_at DESC LIMIT {int(limit)}"
    )
    cols = [c["name"] for c in rows.get("columns", [])] if isinstance(rows, dict) else []
    return [dict(zip(cols, r, strict=False)) for r in rows.get("rows", [])]
